import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync, copyFileSync } from 'node:fs';
import matter from 'gray-matter';
import MarkdownIt from 'markdown-it';
const origin='https://blog.aduroi.com';
const preview = Boolean(process.env.CONTEXT && process.env.CONTEXT !== 'production') || process.env.BLOG_PREVIEW === '1';
const md=new MarkdownIt({html:false,linkify:false,typographer:false});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=data=>JSON.stringify(data).replaceAll('<','\\u003c');
export function isPublic(data) { return data.status==='published' || data.status==='archived'; }
const posts=readdirSync('content/blog').filter(f=>f.endsWith('.md')).map(file=>{
 const {data,content}=matter(readFileSync(`content/blog/${file}`,'utf8'));
 const slug=file.slice(0,-3); if(!/^[a-z0-9-]+$/.test(slug)) throw Error(`Unsafe slug: ${slug}`);
 if(!isPublic(data)) return null;
 for(const key of ['title','description','date','reviewed','author','topic']) if(!data[key]) throw Error(`${file}: missing ${key}`);
 return {...data,date:new Date(data.date).toISOString(),url:`/blog/${slug}/`,slug,content};
}).filter(Boolean).sort((a,b)=> b.reviewed.localeCompare(a.reviewed)||b.date.localeCompare(a.date));
const publicPosts=posts.filter(p=>p.status==='published');
const archive=posts.filter(p=>p.status==='archived');
const wordmark='<span class="wordmark">ADU<span>roi</span></span>';
const header=`<a class="skip" href="#main">Skip to content</a><header class="site-header"><a href="https://aduroi.com/" aria-label="ADUroi home">${wordmark}</a><nav aria-label="Main navigation"><a href="https://aduroi.com/">Product</a><a href="/">Learn</a><a class="button secondary" href="https://app.aduroi.com/">Sign in</a></nav></header>`;
const footer=`<footer class="site-footer"><a href="https://aduroi.com/" aria-label="ADUroi home">${wordmark}</a><p>Make the ADU decision clearer.</p><nav aria-label="Footer navigation"><a href="https://aduroi.com/">Product</a><a href="/">Guides</a><a href="/archive/">Historical archive</a><a href="https://app.aduroi.com/">Sign in</a><a href="/rss.xml">RSS</a></nav><p class="fine">Educational planning information, not a contractor bid, lender approval, appraisal, or legal or tax advice. Results depend on your assumptions.</p></footer>`;
function shell({title,description,url,body,noindex=false,article}) {
 const canonical=origin+url;
 noindex = noindex || preview;
 const structured=article? {'@context':'https://schema.org','@type':'Article',headline:article.title,description:article.description,author:{'@type':article.author==='Grant Olsen'?'Person':'Organization',name:article.author},publisher:{'@type':'Organization',name:'ADUroi'},datePublished:article.date,dateModified:article.reviewed,image:`${origin}/social-card.png`,mainEntityOfPage:canonical,url:canonical}:null;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | ADUroi</title><meta name="description" content="${esc(description)}"><meta name="robots" content="${noindex?'noindex, follow':'index, follow'}"><link rel="canonical" href="${canonical}"><meta property="og:type" content="${article?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="ADUroi"><meta property="og:image" content="${origin}/social-card.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="ADUroi: Make the ADU decision clearer"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="twitter:image" content="${origin}/social-card.png"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><link rel="alternate" type="application/rss+xml" title="ADUroi guides" href="/rss.xml">${structured?`<script type="application/ld+json">${json(structured)}</script>`:''}</head><body>${header}<main id="main" tabindex="-1">${body}</main>${footer}</body></html>`;
}
const cta=p=>`<aside class="callout" aria-label="Planning next step"><p class="eyebrow">Your next step</p><p>${esc(p.cta||'Put the assumptions behind your ADU decision in one place.')}</p><a class="button" href="https://aduroi.com/">Explore ADUroi</a><p class="fine">Results depend on your assumptions. Verify costs, financing, and local requirements before committing.</p></aside>`;
const card=p=>`<article class="card"><p class="eyebrow">${esc(p.topic)}</p><h3><a href="${p.url}">${esc(p.title)}</a></h3><p>${esc(p.description)}</p><p class="fine">${p.status==='archived'?'Historical archive':'Reviewed '+p.reviewed}</p><a href="${p.url}" aria-label="Read ${esc(p.title)}">Read guide <span aria-hidden="true">↗</span></a></article>`;
function write(path,content){mkdirSync(`public/${path.split('/').slice(0,-1).join('/')}`,{recursive:true});writeFileSync(`public/${path}`,content);}
// Clean stale output before any copying. Drafts and original assets are never copied.
rmSync('public',{recursive:true,force:true}); mkdirSync('public',{recursive:true});
copyFileSync('static/styles.css','public/styles.css');copyFileSync('static/favicon.svg','public/favicon.svg');copyFileSync('static/social-card.png','public/social-card.png');
mkdirSync('public/fonts',{recursive:true});
copyFileSync('node_modules/@fontsource/inter/LICENSE','public/fonts/LICENSE');
for(const weight of [400,500,600,700,800]) copyFileSync(`node_modules/@fontsource/inter/files/inter-latin-${weight}-normal.woff2`,`public/fonts/inter-${weight}.woff2`);
write('index.html',shell({title:'ADU guides for a clearer financial decision',description:'Practical ADU guides on cash flow, construction budgets, rent, financing, and the decisions facing homeowners, buyers, and investors.',url:'/',body:`<section class="hero"><p class="eyebrow">The ADUroi field guide</p><h1>Good decisions start with better questions.</h1><p class="lede">What could an ADU change for your monthly cash flow? Start with the assumptions, understand the tradeoffs, and know what to check before you build.</p><a class="button" href="#start">Find your starting point</a></section><section id="start" class="section"><div class="section-heading"><p class="eyebrow">Start here</p><h2>Build a comparison you can question.</h2><p>Practical reading for a home you own, a home you might buy, or an investment property.</p></div><div class="grid">${publicPosts.filter(p=>p.featured).map(card).join('')}</div></section><section class="section"><div class="section-heading"><p class="eyebrow">Keep learning</p><h2>Work through the details.</h2></div><div class="grid">${publicPosts.filter(p=>!p.featured).map(card).join('')}</div></section><section class="archive-note"><h2>Looking for an older article?</h2><p>We keep original URLs and publication dates. Historical law summaries and unverified company comparisons are clearly marked, not passed off as current advice.</p><a href="/archive/">Browse the historical archive</a></section>`}));
for(const p of posts){
 let html=md.render(p.content);
 // Insert an intent-specific CTA after the first section, without client JavaScript.
 const nextHeading=html.indexOf('<h2>',html.indexOf('<h2>')+4); if(nextHeading>0) html=html.slice(0,nextHeading)+cta(p)+html.slice(nextHeading);
 const related=publicPosts.filter(x=>x.url!==p.url).sort((a,b)=>Number(b.topic===p.topic)-Number(a.topic===p.topic)).slice(0,2);
 const notice=p.status==='archived'?`<aside class="notice"><h2>Historical archive</h2><p>${esc(p.archiveReason)} This page remains available at its original URL but is excluded from search indexing and the sitemap.</p></aside>`:'';
 write(`${p.url.slice(1)}index.html`,shell({title:p.title,description:p.description,url:p.url,noindex:p.status==='archived',article:p,body:`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Learn</a><span aria-hidden="true">/</span><span>${esc(p.topic)}</span></nav><article class="reading"><header class="article-header"><p class="eyebrow">${esc(p.topic)}</p><h1>${esc(p.title)}</h1><p class="lede">${esc(p.description)}</p><p class="metadata">By ${esc(p.author)}<br>Originally published <time datetime="${p.date}">${p.date.slice(0,10)}</time> · ${p.status==='archived'?'Archive notice added':'Reviewed and updated'} <time datetime="${p.reviewed}">${p.reviewed}</time></p></header>${notice}<p class="disclaimer">Planning information only. Confirm local requirements and review financing, tax treatment, scope, and costs with the appropriate professionals.</p><div class="prose">${html}</div>${cta(p)}</article><section class="section related"><h2>Keep working on the decision</h2><div class="grid two">${related.map(card).join('')}</div></section>`}));
}
write('archive/index.html',shell({title:'Historical ADU article archive',description:'Older ADU policy and company coverage, with original dates retained and clear warnings where the information is no longer current.',url:'/archive/',noindex:true,body:`<section class="hero"><p class="eyebrow">Original dates. Clear context.</p><h1>Historical archive</h1><p class="lede">These articles record earlier coverage. They are not current legal guidance or verified service comparisons.</p></section><section class="section"><h2>Older coverage</h2><div class="grid">${archive.map(card).join('')}</div></section>`}));
write('blog/index.html',shell({title:'All ADU guides',description:'Browse ADUroi guides and historical articles about accessory dwelling unit decisions.',url:'/blog/',noindex:true,body:`<section class="hero"><h1>All ADU guides</h1><p class="lede">Current guides and clearly marked historical coverage.</p></section><section class="section"><h2>Article library</h2><div class="grid">${posts.map(card).join('')}</div></section>`}));
write('404.html',shell({title:'Page not found',description:'This ADUroi page could not be found. Browse the guides to continue.',url:'/404.html',noindex:true,body:'<section class="hero"><h1>That page is not here.</h1><p>Try the guide library or check the article address.</p><a class="button" href="/">Browse ADU guides</a></section>'}));
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>${origin}/</loc></url>${publicPosts.map(p=>`<url><loc>${origin}${p.url}</loc><lastmod>${p.reviewed}</lastmod></url>`).join('')}</urlset>`);
write('robots.txt',preview ? 'User-agent: *\nDisallow: /\n' : `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
write('_headers', `/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n${preview?'  X-Robots-Tag: noindex, nofollow, noarchive\n':''}/sw.js\n  Cache-Control: no-cache, no-store, must-revalidate\n`);
// Retire the former Gatsby offline worker for returning visitors. No new worker is registered.
write('sw.js', `self.addEventListener('install',()=>self.skipWaiting());self.addEventListener('activate',event=>event.waitUntil(self.registration.unregister()));\n`);
write('rss.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>ADUroi guides</title><link>${origin}/</link><description>Practical reading for ADU decisions.</description>${publicPosts.map(p=>`<item><title>${esc(p.title)}</title><link>${origin}${p.url}</link><guid>${origin}${p.url}</guid><pubDate>${new Date(p.date).toUTCString()}</pubDate><description>${esc(p.description)}</description></item>`).join('')}</channel></rss>`);
console.log(`Built ${posts.length} articles (${publicPosts.length} current, ${archive.length} historical); drafts excluded. Output: public/`);
